### ISSUE TITLE
Modbus communication is very slow

### ISSUE THREAD

**Issue by mzfhhhh** [deviator/modbus#10]
On the windows platform,
when I need to read 6 registers,
Use serialport sends data directly, only about 30ms.
Instead modbus sends and requires 48ms!

**Comment by deviator** [comment]
You say about [`serialport`](https://github.com/deviator/serialport)? It use non-blocking reading and writing and it sleep every not-complete reading or writing (need for using in fibers). For example if it read or write 8 of expected 10 bytes it sleep [`Duration ioPause()`](https://github.com/deviator/serialport/blob/master/source/serialport/port.d#L47). Sleep time in `serailport` calculates based on assumption that new data can't be received faster that one byte fully received: (8 data bits + 1 start bit + 1 stop bit) / baudrate, for baudrate = 9600 `ioPause()` approx returns `1ms`. Modbus have no information about baudrate because use [`interface Connection`](https://github.com/deviator/modbus/blob/master/source/modbus/connection.d) that have only `read` and `write` methods. Modbus use [`writeStepPause`](https://github.com/deviator/modbus/blob/master/source/modbus/protocol/base.d#L64) and [`readStepPause`](https://github.com/deviator/modbus/blob/master/source/modbus/protocol/master.d#L14) public fields for determine sleep time (orient to speed=9600). I think I fix it for `ModbusRTUMaster` specially (it use `SerialPort` by default and can get `baudRate` from it).

That speed are you using? You say serialport **sends data** is it's mean `writeLoop` method or `write` method? Reading registers means `write` message to serial port and `read` response from it. Did you measure only sending (`write`) or sending and receiving (`request` = `write` + `read`)?

**Comment by mzfhhhh** [comment]
i use your serialport package to send and receive raw modbus data. the total time is 30ms.
baudrate is 19200.
but use your modbus rtu package send and receive is 48ms.

and then i test with other modbus libraries is also 30ms.so i think your modbus-rtu implement have some probleam.

**Comment by deviator** [comment]
In this moment I can't test it (no any modbus device at hand), but I change read and write step pause behavior in last commit 54a55e40691ca45df2d7e206e46cd2b4221c568c
Can you try and inform me about result?

**Comment by mzfhhhh** [comment]
hi, it's my mistake,
before i test it with modbus-0.7.2.
now i fetch the modbus-0.9.1 and the results is ok,both 30ms.

thanks !!!

**Comment by deviator** [comment]
I rework read code and it's must work fine in all cases: short requests and long requests, rtu and tcp.
And I think issue can be closed.
@mzfhhhh if you detect speed problem inform me please.
